# Dependencies
highlighter:      rouge

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            "Countering Race-Based Medicine"
tagline:          ""
description:      "A practical guide for health professionals"
url: https://ayzhang93.github.io
# baseurl:          counteringracebasedmed/

author:
  name:           "Medical students nationwide"
  url:

paginate:         5

collections:
  definitions:
    output: true
    name: "Introduction & Definitions"
    info: true
    order: 1
  conditions:
    output: true
    name: "Conditions"
    info: true
    order: 2
  medications:
    output: true
    name: "Medications"
    info: true
    order: 3
  calculators:
    output: true
    name: "Calculators and Adjustments"
    info: true
    order: 4


# Custom vars
version:          2.1.0 # for zip download and sidebar note

github:
  repo:          https://github.com/ayzhang93/counteringracebasedmed/
