# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            "Countering Race-Based Medicine"
tagline:          "A Practical Guide"
description:      "Race, a social construct, is problematically biologicized in medicine...more description here"
url:
baseurl:          /

author:
  name:           "Medical students nationwide"
  url:

paginate:         5

collections:
  calculators:
    output: true
  conditions:
    output: true
  definitions:
    output: true
  medications:
    output: true


# Custom vars
version:          2.1.0

github:
  repo:          https://github.com/ayzhang93/counteringracebasedmed/
