# Dependencies
highlighter:      rouge

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            "Countering Race-Based Medicine"
tagline:          "A Practical Guide"
description:      "Race, a social construct, is problematically biologicized in medicine...more description here"
url: https://ayzhang93.github.io/counteringracebasedmed/
# baseurl:          counteringracebasedmed/

author:
  name:           "Medical students nationwide"
  url:

paginate:         5

collections:
  definitions:
    output: true
    name: "Introduction & Definitions"
    info: true
  conditions:
    output: true
    name: "Conditions"
    info: true
  medications:
    output: true
    name: "Medications"
    info: true
  calculators:
    output: true
    name: "Calculators and Adjustments"
    info: true


# Custom vars
version:          2.1.0 # for zip download and sidebar note

github:
  repo:          https://github.com/ayzhang93/counteringracebasedmed/
