# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            "Countering Race-Based Medicine"
tagline:          "A Practical Guide"
description:      "Race, a social construct, is problematically biologicized in medicine...more description here"
url: https://ayzhang93.github.io/
baseurl:          counteringracebasedmed/

author:
  name:           "Medical students nationwide"
  url:

paginate:         5

collections:
  calculators:
    output: true
    label: "Calculators and Adjustments"
  conditions:
    output: true
    label: "Conditions"
  definitions:
    output: true
    label: "Introduction & Definitions"
  medications:
    output: true
    label: "Medications"


# Custom vars
version:          2.1.0 # for zip download and sidebar note

github:
  repo:          https://github.com/ayzhang93/counteringracebasedmed/
